spring:
  thymeleaf:
    cache: false
    #prefix: file:src/main/resources/templates

  freemarker:
    enabled: false

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  messages:
    basename: messages/**
    encoding: UTF-8

  datasource:
    url: jdbc:h2:tcp://localhost/C:\h2\data\mini
    #url: jdbc:h2:tcp://localhost/C:\h2\data\mini;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

