spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/  #prefix를 적용하면 html을 찾지 못 함

  freemarker:
    enabled: false

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  messages:
    basename: message/messages  #message 파일을 여러개 사용할 경우 콤마로 구분해서 여러개의 basename을 설정할 수 있다. classpath:/message/messages  --> 적용 안 됨
    cache-duration: 3 #캐시 주기 설정, 기본 값 forever(-1)
    #cache-seconds: 3
    encoding: UTF-8
    fallback-to-system-locale: false #감지된 locale에 대한 파일이 없는 경우, 설정값 true : system locale 사용, 설정값 false : messages.properties 파일을 사용
    use-code-as-default-message: true #메시지를 찾지 못했을 때, 예외 처리 대신 메시지 코드를 그대로 반환
    #always-use-message-format=false #MessasgeFormat을 전체 메시지에 적용할 것인지   

  datasource:
    url: jdbc:h2:tcp://localhost/C:\h2\data\mini  # ;MVCC=TRUE 옵션 적용시 오류 발생 함
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  #file: logs/miniApplication.log
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

